import dynamic from 'next/dynamic';

export type SectionRegistryEntry = {
  id: string;
  name: string;
  description: string;
  category: string;
  component: React.ComponentType<any>;
};

export const sections: Record<string, SectionRegistryEntry> = {
  "hero-1": {
    id: "hero-1",
    name: "Hero Section 1",
    description: "A placeholder hero section to test the registry pipeline.",
    category: "hero",
    component: dynamic(() => import('@/components/sections/hero/Hero1')),
  },
  "glow-card-demo": {
    id: "glow-card-demo",
    name: "Spotlight Glow Card Demo",
    description: "Demo of the spotlight glow card component.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/GlowCardDemo')),
  },
  "animated-cards-demo": {
    id: "animated-cards-demo",
    name: "Animated Cards Stack Demo",
    description: "A scrolling animated cards stack component.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/AnimatedCardsDemo')),
  },
  "bouncy-accordion-demo": {
    id: "bouncy-accordion-demo",
    name: "Bouncy Accordion Demo",
    description: "A spring-animated bouncy accordion component.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/BouncyAccordionDemo')),
  },
  "trail-grid-demo": {
    id: "trail-grid-demo",
    name: "Trail Grid Demo",
    description: "An interactive background grid that trails the mouse cursor.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/TrailGridDemo')),
  },
  "sticky-scroll-cards-demo": {
    id: "sticky-scroll-cards-demo",
    name: "Sticky Scroll Cards Demo",
    description: "A section where feature cards stack responsively as you scroll.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/StickyScrollCardsDemo')),
  },
  "feature-carousel-demo": {
    id: "feature-carousel-demo",
    name: "Feature Carousel Demo",
    description: "An animated, auto-playing carousel of features with dynamic image transitions.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/FeatureCarouselDemo')),
  },
  "background-paths-demo": {
    id: "background-paths-demo",
    name: "Background Paths Demo",
    description: "A gorgeous animated SVG background path component with staggered text.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/BackgroundPathsDemo')),
  },
  "shaders-hero-demo": {
    id: "shaders-hero-demo",
    name: "Shaders Hero Demo",
    description: "An immersive landing page hero section utilizing advanced WebGL shaders.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/ShadersHeroDemo')),
  },
  "the-infinite-grid-demo": {
    id: "the-infinite-grid-demo",
    name: "The Infinite Grid Demo",
    description: "An infinitely scrolling background grid pattern with a cursor spotlight effect.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/TheInfiniteGridDemo')),
  },
  "particle-effect-hero-demo": {
    id: "particle-effect-hero-demo",
    name: "Particle Effect Hero Demo",
    description: "A highly interactive, physics-based 2D canvas particle simulation.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/ParticleEffectHeroDemo')),
  },
  "morphing-card-stack-demo": {
    id: "morphing-card-stack-demo",
    name: "Morphing Card Stack Demo",
    description: "A card container that smoothly morphs between stack, grid, and list layouts.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/MorphingCardStackDemo')),
  },
  "hero-shutter-text-demo": {
    id: "hero-shutter-text-demo",
    name: "Hero Shutter Text Demo",
    description: "A highly stylized typographic Hero component with shutter slicing text animation.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/HeroShutterTextDemo')),
  },
  "glowy-waves-hero-demo": {
    id: "glowy-waves-hero-demo",
    name: "Glowy Waves Hero Demo",
    description: "A highly responsive interactive canvas hero with glowing math-based waves.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/GlowyWavesHeroDemo')),
  },
  "pixel-hero-demo": {
    id: "pixel-hero-demo",
    name: "Pixel Hero Demo",
    description: "A minimalist hero section with a staggered pixel background physics engine.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/PixelHeroDemo')),
  },
  "mesh-hero-variants-demo": {
    id: "mesh-hero-variants-demo",
    name: "Mesh Hero Variants Demo",
    description: "A showcase of 5 different mesh gradient hero variations.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/MeshHeroVariantsDemo')),
  },
  "clipped-video-tab-demo": {
    id: "clipped-video-tab-demo",
    name: "Clipped Video Tab Demo",
    description: "A highly interactive video tab layout with custom polygon clipping masks.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/ClippedVideoTabDemo')),
  },
  "feature-shader-cards-demo": {
    id: "feature-shader-cards-demo",
    name: "Feature Shader Cards Demo",
    description: "A grid of feature cards backed by performant WebGL shaders with unique configs.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/FeatureShaderCardsDemo')),
  },
  "halide-topo-hero-demo": {
    id: "halide-topo-hero-demo",
    name: "Halide Topo Hero Demo",
    description: "A topographic, brutalist 3D parallax hero with grain filters and nested 3D layers.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/HalideTopoHeroDemo')),
  },
  "hand-writing-text-demo": {
    id: "hand-writing-text-demo",
    name: "Hand Written Title Demo",
    description: "An animated hand written title using framer motion.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/HandWrittenTitleDemo')),
  },
  "aurora-borealis-shader-demo": {
    id: "aurora-borealis-shader-demo",
    name: "Aurora Borealis Shader Demo",
    description: "An interactive WebGL shader of the Aurora Borealis using Three.js.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/AuroraBorealisShaderDemo')),
  },
  "feature-with-image-comparison-demo": {
    id: "feature-with-image-comparison-demo",
    name: "Feature With Image Comparison Demo",
    description: "A feature section with an interactive image comparison slider.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/FeatureWithImageComparisonDemo')),
  },
  "display-cards-demo": {
    id: "display-cards-demo",
    name: "Display Cards Demo",
    description: "An elegant, interactive stack of overlapping display cards.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/DisplayCardsDemo')),
  },
  "premium-hero-demo": {
    id: "premium-hero-demo",
    name: "Premium Hero Demo",
    description: "An AI-focused premium hero with animated beam backgrounds.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/PremiumHeroDemo')),
  },
  "hero-section-1-demo": {
    id: "hero-section-1-demo",
    name: "Hero Section 1 Demo",
    description: "A dark futuristic hero section with user avatars and a waitlist form.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/HeroSection1Demo')),
  },
  "aether-flow-hero-demo": {
    id: "aether-flow-hero-demo",
    name: "Aether Flow Hero Demo",
    description: "An adaptive framework for fluid digital experiences with particles.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/AetherFlowHeroDemo')),
  },
  "interactive-robot-spline-demo": {
    id: "interactive-robot-spline-demo",
    name: "Interactive Robot Spline Demo",
    description: "An interactive 3D robot scene using Spline.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/InteractiveRobotSplineDemo')),
  },
  "gradient-dots-demo": {
    id: "gradient-dots-demo",
    name: "Gradient Dots Demo",
    description: "Animated background layer with gradient hex dots and hue shifting.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/GradientDotsDemo')),
  },
  "turing-landing-demo": {
    id: "turing-landing-demo",
    name: "Turing Landing Demo",
    description: "A flagship hero landing element with immersive background video.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/TuringLandingDemo')),
  },
  "cybernetic-grid-shader-demo": {
    id: "cybernetic-grid-shader-demo",
    name: "Cybernetic Grid Shader Demo",
    description: "An interactive WebGL background shader reacting to mouse movement.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/CyberneticGridShaderDemo')),
  },
  "typewriter-demo": {
    id: "typewriter-demo",
    name: "Typewriter Demo",
    description: "A typewriter effect rotating through strings sequentially.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/TypewriterDemo')),
  },
  "modern-animated-multi-words-demo": {
    id: "modern-animated-multi-words-demo",
    name: "Modern Animated Multi Words Demo",
    description: "A modern animated multi words component with glowing backgrounds.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/ModernAnimatedMultiWordsDemo')),
  },
  "holographic-card-demo": {
    id: "holographic-card-demo",
    name: "Holographic Card Demo",
    description: "An interactive holographic card that reacts to mouse movement.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/HolographicCardDemo')),
  },
  "cover-demo": {
    id: "cover-demo",
    name: "Cover Demo",
    description: "A text cover component with animated particle beams on hover.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/CoverDemo')),
  },
  "hero-section-demo": {
    id: "hero-section-demo",
    name: "Financial Hero Demo",
    description: "A modern financial SaaS hero section with tilted cards.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/hero-section-demo')),
  },
  "hero-section-5-demo": {
    id: "hero-section-5-demo",
    name: "Hero Section 5 Demo",
    description: "A comprehensive SaaS hero with an infinite client slider and progressive blur.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/hero-section-5-demo')),
  },
  "background-boxes-demo": {
    id: "background-boxes-demo",
    name: "Background Boxes Demo",
    description: "An interactive grid of boxes that light up on hover.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/background-boxes-demo')),
  },
  "vapour-text-effect-demo": {
    id: "vapour-text-effect-demo",
    name: "Vapour Text Effect Demo",
    description: "A high-performance HTML canvas text vaporization effect.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/vapour-text-effect-demo')),
  },
  "wave-path-demo": {
    id: "wave-path-demo",
    name: "Wave Path Demo",
    description: "An interactive SVG wave path that reacts to mouse movements.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/wave-path-demo')),
  },
  "text-parallax-content-demo": {
    id: "text-parallax-content-demo",
    name: "Text Parallax Content Demo",
    description: "A scrolling parallax text reveal component.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/text-parallax-content-demo').then((m) => m.TextParallaxContentDemo)),
  },
  "features-9-demo": {
    id: "features-9-demo",
    name: "Features 9 Demo",
    description: "A comprehensive features section with charts and map.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/features-9-demo').then((m) => m.Features9Demo)),
  },
  "testimonial-slider-demo": {
    id: "testimonial-slider-demo",
    name: "Testimonial Slider Demo",
    description: "A smooth framer motion testimonial carousel.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/testimonial-slider-demo').then((m) => m.TestimonialSliderDemo)),
  },
  "meteors-demo": {
    id: "meteors-demo",
    name: "Meteors Demo",
    description: "A cool meteor shower animation effect.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/meteors-demo').then((m) => m.MeteorsDemo)),
  },
  "3d-testimonails-demo": {
    id: "3d-testimonails-demo",
    name: "3D Testimonials Marquee Demo",
    description: "A multi-column 3D perspective scrolling marquee.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/3d-testimonails-demo').then((m) => m.Testimonials3DDemo)),
  },
  "pricing-demo": {
    id: "pricing-demo",
    name: "Pricing Cards Demo",
    description: "Animated pricing cards with a toggle switch.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/pricing-demo').then((m) => m.PricingBasic)),
  },
  "category-list-demo": {
    id: "category-list-demo",
    name: "Category List Demo",
    description: "Interactive expanding category cards on hover.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/category-list-demo').then((m) => m.CategoryListDemo)),
  },
  "a-modern-hero-section-demo": {
    id: "a-modern-hero-section-demo",
    name: "A Modern Hero Section Demo",
    description: "A modern hero section with randomized pixel grids.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/a-modern-hero-section-demo').then((m) => m.DemoOne)),
  },
  "rotating-gradient-right-demo": {
    id: "rotating-gradient-right-demo",
    name: "Rotating Gradient Right Demo",
    description: "A glowing conic gradient spinning behind a glass card.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/rotating-gradient-right-demo')),
  },
  "parallax-floating-demo": {
    id: "parallax-floating-demo",
    name: "Parallax Floating Demo",
    description: "Interactive depth mapping of elements based on mouse movement.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/parallax-floating-demo').then((m) => m.ParallaxFloatingDemo)),
  },
  "chapter-scrubber-demo": {
    id: "chapter-scrubber-demo",
    name: "Chapter Scrubber Demo",
    description: "A slick, buttery smooth iOS-style scrolling chapter rail.",
    category: "demo",
    component: dynamic(() => import('@/components/sections/demo/chapter-scrubber-demo').then((m) => m.ChapterScrubberDemo)),
  }
};
